In [1]:
import numpy as np

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [12]:
array = np.random.rand(2, 3, 5)
array_redondeado = np.round(array, 1)
print(array_redondeado)

[[[0.4 0.5 0.6 0.5 0.5]
  [0.9 0.4 0.7 0.9 0.2]
  [0.1 0.5 0.7 0.2 0.6]]

 [[0.5 0.7 0.9 0.9 0. ]
  [0.4 0.7 0.5 0.6 0.7]
  [0.9 0.6 0.7 0.9 1. ]]]


2.Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [15]:
array_vacio = np.empty((2, 3, 5))
print(array_vacio)

[[[0.58664472 0.3420398  0.0404798  0.04913489 0.95463838]
  [0.79169422 0.11149737 0.58871898 0.58880793 0.54263841]
  [0.40994194 0.24144732 0.73690062 0.38687455 0.82112457]]

 [[0.9925468  0.78944936 0.59046757 0.83697843 0.42633012]
  [0.52862109 0.49373017 0.72573867 0.32145919 0.84912503]
  [0.46271142 0.15397307 0.14977854 0.74649313 0.97258499]]]


In [19]:
media = np.mean(array_vacio)
print(media)

0.5410857029217752


In [18]:
array1 = np.where(array_vacio == media, 'A', array_vacio)
print(array1)

[[['0.5866447228357766' '0.34203979878704793' '0.040479796185345696'
   '0.049134894641937876' '0.9546383838604651']
  ['0.7916942220822898' '0.11149736632738172' '0.5887189819050297'
   '0.5888079265422939' '0.5426384072026738']
  ['0.40994193827129566' '0.241447320519094' '0.7369006178541654'
   '0.386874546255785' '0.8211245719200522']]

 [['0.9925467979535073' '0.7894493628999308' '0.5904675737554962'
   '0.8369784309501958' '0.42633011997409376']
  ['0.5286210905193196' '0.49373016773079237' '0.7257386702006879'
   '0.32145918883740654' '0.8491250329332001']
  ['0.46271142218315564' '0.15397307175703445' '0.1497785429236238'
   '0.7464931329114715' '0.9725849869327028']]]


In [20]:
array2 = np.where(array_vacio > media, 'B', array_vacio)
print(array2)

[[['B' '0.34203979878704793' '0.040479796185345696'
   '0.049134894641937876' 'B']
  ['B' '0.11149736632738172' 'B' 'B' 'B']
  ['0.40994193827129566' '0.241447320519094' 'B' '0.386874546255785' 'B']]

 [['B' 'B' 'B' 'B' '0.42633011997409376']
  ['0.5286210905193196' '0.49373016773079237' 'B' '0.32145918883740654'
   'B']
  ['0.46271142218315564' '0.15397307175703445' '0.1497785429236238' 'B'
   'B']]]


In [21]:
array3 = np.where(array_vacio < media, 'C', array_vacio)
print(array3)

[[['0.5866447228357766' 'C' 'C' 'C' '0.9546383838604651']
  ['0.7916942220822898' 'C' '0.5887189819050297' '0.5888079265422939'
   '0.5426384072026738']
  ['C' 'C' '0.7369006178541654' 'C' '0.8211245719200522']]

 [['0.9925467979535073' '0.7894493628999308' '0.5904675737554962'
   '0.8369784309501958' 'C']
  ['C' 'C' '0.7257386702006879' 'C' '0.8491250329332001']
  ['C' 'C' 'C' '0.7464931329114715' '0.9725849869327028']]]


In [23]:
maximo = np.max(array_vacio)
array4 = np.where(array_vacio == maximo, 'D', array_vacio)
print(array4)

[[['0.5866447228357766' '0.34203979878704793' '0.040479796185345696'
   '0.049134894641937876' '0.9546383838604651']
  ['0.7916942220822898' '0.11149736632738172' '0.5887189819050297'
   '0.5888079265422939' '0.5426384072026738']
  ['0.40994193827129566' '0.241447320519094' '0.7369006178541654'
   '0.386874546255785' '0.8211245719200522']]

 [['D' '0.7894493628999308' '0.5904675737554962' '0.8369784309501958'
   '0.42633011997409376']
  ['0.5286210905193196' '0.49373016773079237' '0.7257386702006879'
   '0.32145918883740654' '0.8491250329332001']
  ['0.46271142218315564' '0.15397307175703445' '0.1497785429236238'
   '0.7464931329114715' '0.9725849869327028']]]


In [25]:
minimo = np.min(array_vacio)
array5 = np.where(array_vacio == minimo, 'E', array_vacio)
print(array5)

[[['0.5866447228357766' '0.34203979878704793' 'E' '0.049134894641937876'
   '0.9546383838604651']
  ['0.7916942220822898' '0.11149736632738172' '0.5887189819050297'
   '0.5888079265422939' '0.5426384072026738']
  ['0.40994193827129566' '0.241447320519094' '0.7369006178541654'
   '0.386874546255785' '0.8211245719200522']]

 [['0.9925467979535073' '0.7894493628999308' '0.5904675737554962'
   '0.8369784309501958' '0.42633011997409376']
  ['0.5286210905193196' '0.49373016773079237' '0.7257386702006879'
   '0.32145918883740654' '0.8491250329332001']
  ['0.46271142218315564' '0.15397307175703445' '0.1497785429236238'
   '0.7464931329114715' '0.9725849869327028']]]


In [55]:
array_final = np.where(array_vacio == media, 'A', np.where(array_vacio > media, 'B', np.where(array_vacio < media, 'C',  np.where(array_vacio == maximo, 'D', np.where(array_vacio == minimo, 'E', array_vacio)))))
print(array_final)

[[['B' 'C' 'C' 'C' 'B']
  ['B' 'C' 'B' 'B' 'B']
  ['C' 'C' 'B' 'C' 'B']]

 [['B' 'B' 'B' 'B' 'C']
  ['C' 'C' 'B' 'C' 'B']
  ['C' 'C' 'C' 'B' 'B']]]


BONUS
1. Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [56]:
random = np.random.randint(0, 101, (2,3,5))
print(random)

[[[79 99  8 70 14]
  [64 75 15 67 35]
  [97 78 57 69 85]]

 [[80 15  3 77  0]
  [31 53 93 67  9]
  [62 33 94  0 26]]]


In [60]:
random[ :, :, ::3]

array([[[79, 70],
        [64, 67],
        [97, 69]],

       [[80, 77],
        [31, 67],
        [62,  0]]])

In [61]:
r = np.where(random[ :, :, ::3], 0, random)
print(r)


ValueError: operands could not be broadcast together with shapes (2,3,2) () (2,3,5) 